export const tipoOptions = [
  { value: "PF", label: "Pessoa Fisica" },
  { value: "PJ", label: "Pessoa Juridica" },
  { value: "PUBLICO", label: "Instituicao Publica" },
  { value: "PRIVADO", label: "Instituicao Privada" },
] as const;

export const bancoOptions = [
  "001 - BCO DO BRASIL S.A.",
  "003 - BCO DA AMAZONIA S.A.",
  "004 - BCO DO NORDESTE DO BRASIL S.A.",
  "007 - BNDES",
  "033 - BCO SANTANDER (BRASIL) S.A.",
  "036 - BCO BBI S.A.",
  "037 - BCO DO EST. DO PA S.A.",
  "040 - BCO CARGILL S.A.",
  "069 - BCO CREFISA S.A.",
  "070 - BRB - BCO DE BRASILIA S.A.",
  "077 - BANCO INTER",
  "079 - PICPAY BANK - BANCO MULTIPLO S.A",
  "096 - BCO B3 S.A.",
  "102 - XP INVESTIMENTOS CCTVM S/A",
  "104 - CAIXA ECONOMICA FEDERAL",
  "136 - UNICRED DO BRASIL",
  "208 - BANCO BTG PACTUAL S.A.",
  "233 - BANCO CIFRA",
  "237 - BCO BRADESCO S.A.",
  "250 - BANCO BMG CONSIGNADO S.A.",
  "260 - NUBANK PAGAMENTOS - IP",
  "290 - PAGSEGURO INTERNET IP S.A.",
  "323 - MERCADO PAGO IP LTDA.",
  "336 - BCO C6 S.A.",
  "341 - ITAU UNIBANCO S.A.",
  "362 - CIELO IP S.A.",
  "380 - PICPAY",
  "386 - NUBANK FINANCEIRA S.A. CFI",
  "389 - BCO MERCANTIL DO BRASIL S.A.",
  "403 - CORA SCFI",
  "422 - BCO SAFRA S.A.",
  "477 - CITIBANK N.A.",
  "536 - NEON PAGAMENTOS S.A. IP",
  "623 - BANCO PAN",
  "707 - BCO DAYCOVAL S.A",
  "748 - BCO COOPERATIVO SICREDI S.A.",
  "756 - BANCO SICOOB S.A.",
  "Outro",
] as const;

export const estadoOptions = [
  "AC",
  "AL",
  "AP",
  "AM",
  "BA",
  "CE",
  "DF",
  "ES",
  "GO",
  "MA",
  "MT",
  "MS",
  "MG",
  "PA",
  "PB",
  "PR",
  "PE",
  "PI",
  "RJ",
  "RN",
  "RS",
  "RO",
  "RR",
  "SC",
  "SP",
  "SE",
  "TO",
] as const;
